### ISSUE TITLE
Can't find profile in Steam

### ISSUE THREAD

**Issue by JPRuskin** [trankillity/deck_diablo3#1]
When trying to load this profile from the control setup screen, there is no config matching this description.

My game is titled 'Diablo III', and i don't think it's case sensitive.

If the raw config could be uploaded here, that would solve:
- [Docs] Upload raw config file for people to download directly.
- and allow me to use it

The file can be found here, on my deck: `/home/deck/.local/share/Steam/steamapps/common/Steam Controller Configs/{USERID}/config/diablo iii/controller_neptune.vdf`

**Comment by trankillity** [comment]
Thanks for the interest. I have significantly improved the layout since this was uploaded after about 50 hours on the Barb, but haven't uploaded it yet. In the mean time, I have updated the documentation with an alternate method to access the profile.

> Paste this into Konsole in desktop mode on your Steam Deck - `xdg-open steam://controllerconfig/diablo%20iii/2854432738`
